version: '3.8'

services:
  app:
    build: .
    container_name: insta-container
    restart: always
    ports:
      - "5000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - app_network
    

  postgres:
    image: postgres:17-alpine
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: instagram2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network
  

networks:
  app_network:

volumes:
  postgres_data: